### ISSUE TITLE
compute_all isn't really realistic if it only accepts 1 sigma/IV because call/put IVs are usually different

### ISSUE THREAD

**Issue by brandonros** [phillyfan1138/black_scholes_rust#20]
not sure if that's an easy refactor or not... or if I am misunderstanding somethign

**Comment by danielhstahl** [comment]
They aren't different by put-call parity. If there is a difference, there is an arbitrage or the parameters are different.

https://blog.orats.com/understanding-options-why-do-calls-and-puts-have-different-implied-volatility
