### ISSUE TITLE
put_vanna should be negative?

### ISSUE THREAD

**Issue by brandonros** [phillyfan1138/black_scholes_rust#21]
https://www.thebalancemoney.com/vanna-explanation-of-the-options-greek-1031331

>  In options trading, vanna will be negative for put options and positive for call options.

**Comment by danielhstahl** [comment]
The link is wrong; https://en.wikipedia.org/wiki/Greeks_(finance)#Vanna

Vanna is the derivative of delta with respect to sigma.  By put call parity, call_delta-1=put_delta.  Taking the derivative of both sides with respect to sigma, call_delta_dsig=put_delta_dsig.
