### ISSUE TITLE
CDF function is not appropriate, can use statrs package for accurate values.

### ISSUE THREAD

**Issue by dileepbapat** [phillyfan1138/black_scholes_rust#8]
https://github.com/danielhstahl/black_scholes_rust/blob/c5582fa71295b7411a872d0e3a8eaf069edff10e/src/lib.rs#L8
```rust
use statrs::distribution::{Normal, Univariate};

pub fn cum_norm(x: f64) -> f64 {
    // (x / SQRT_2) * 0.5 
    let n = Normal::new(0.0, 1.0).unwrap();
    return n.cdf(x);
}
```

**Comment by danielhstahl** [comment]
What is wrong with erf

**Comment by dileepbapat** [comment]
Please check the values near maturity = 0.25/365.0. Values are way off from standard call value. It turned out replacing CDF gave an appropriate call value.

for example price of an in-the-money call option with 2 hours to expiry should be closer to (spot - strike). 

```
call(14341.0, 14000.0, 0.1, 0.2125, 0.25/365.0)
> 552.5131384979031
should be around 341 
```

right?

**Comment by danielhstahl** [comment]
Ok I'll take a look.

**Comment by danielhstahl** [comment]
Ok I added a PR for the statrs but its slower (as I expected).

I added a test specifically for your function and I get 342 as the call price, not 552....see the test assertion at https://github.com/danielhstahl/black_scholes_rust/pull/10/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R481

**Comment by danielhstahl** [comment]
Long story short:
* Statrs is slower because I didn't cache the creation of the normal distribution struct
* the call price function in my tests (and confirmed by github actions) shows the original (fast) implementation is correct.
